name: Build .NET and Publish to NuGet

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/Eliot.UELib.csproj
    - name: Build
      run: dotnet build src/Eliot.UELib.csproj --no-restore
    - name: Test
      run: dotnet test src/Eliot.UELib.csproj --no-build --verbosity normal
    - name: Publish Eliot.UELib
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Eliot.UELib.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
